version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_DATABASE=trello
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - trello-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - trello-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 5

  # Migration service - runs migrations and seeds
  migration:
    image: baocules/trello:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - trello-network
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        sleep 10 &&
        echo 'Running database migrations...' &&
        npm run typeorm:run &&
        echo 'Running database seed...' &&
        npm run seed &&
        echo 'Migration and seed completed!'
      "
    restart: "no"

  # Main application service
  trello:
    image: baocules/trello:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    networks:
      - trello-network

networks:
  trello-network:
    driver: bridge

volumes:
  mysql_data:
