import express from 'express'
import boardController from './board.controller'
const router: express.Router = express.Router()

router.route('/')
    .post(boardController.createNewBoard)
router.route('/:id')
    .get(boardController.getBoardById)
    .put(boardController.updateBoardById)
    .delete(boardController.deleteBoardById)
router.route('/:id/:field')
    .get(boardController.getFieldFromBoard)
router.route('/:id/lists/')
    .post(boardController.addNewListToBoard)
    .get(boardController.getAllLists)
router.route('/:id/list/:listId')
    .get(boardController.getListById)
    .put(boardController.updateListById)
    .delete(boardController.deleteListById)
router.route('/:id/card/:cardId')
    .get(boardController.getCardFromBoardId)
router.route('/:id/cards')
    .get(boardController.getCardsFromBoardId)
router.route('/:id/members')
    .get(boardController.getAllMemberFromBoardId)
router.route('/:id/member/:idMember')
    .post(boardController.addNewMemberToBoard)
    .put(boardController.updateMemberFromBoard)
    .delete(boardController.deleteMemberFromBoard)